//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spent.Commons.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Spent.Commons.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CompareAttribute_ValidationError {
            get {
                return ResourceManager.GetString("CompareAttribute_ValidationError", resourceCulture);
            }
        }
        
        public static string EmailAddressAttribute_ValidationError {
            get {
                return ResourceManager.GetString("EmailAddressAttribute_ValidationError", resourceCulture);
            }
        }
        
        public static string MaxLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        public static string MinLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MinLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        public static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        public static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        public static string BadRequestException {
            get {
                return ResourceManager.GetString("BadRequestException", resourceCulture);
            }
        }
        
        public static string ConflicException {
            get {
                return ResourceManager.GetString("ConflicException", resourceCulture);
            }
        }
        
        public static string ForbiddenException {
            get {
                return ResourceManager.GetString("ForbiddenException", resourceCulture);
            }
        }
        
        public static string ResourceValidationException {
            get {
                return ResourceManager.GetString("ResourceValidationException", resourceCulture);
            }
        }
        
        public static string RestException {
            get {
                return ResourceManager.GetString("RestException", resourceCulture);
            }
        }
        
        public static string UnauthorizedException {
            get {
                return ResourceManager.GetString("UnauthorizedException", resourceCulture);
            }
        }
        
        public static string UnknownException {
            get {
                return ResourceManager.GetString("UnknownException", resourceCulture);
            }
        }
        
        public static string UpdateConcurrencyException {
            get {
                return ResourceManager.GetString("UpdateConcurrencyException", resourceCulture);
            }
        }
        
        public static string ResourceNotFoundException {
            get {
                return ResourceManager.GetString("ResourceNotFoundException", resourceCulture);
            }
        }
        
        public static string TooManyRequestsExceptions {
            get {
                return ResourceManager.GetString("TooManyRequestsExceptions", resourceCulture);
            }
        }
        
        public static string ServerConnectionException {
            get {
                return ResourceManager.GetString("ServerConnectionException", resourceCulture);
            }
        }
        
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        public static string Alphabetical {
            get {
                return ResourceManager.GetString("Alphabetical", resourceCulture);
            }
        }
        
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        public static string EditProfileTitle {
            get {
                return ResourceManager.GetString("EditProfileTitle", resourceCulture);
            }
        }
        
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        public static string TermsTitle {
            get {
                return ResourceManager.GetString("TermsTitle", resourceCulture);
            }
        }
        
        public static string ProfileUpdatedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("ProfileUpdatedSuccessfullyMessage", resourceCulture);
            }
        }
        
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string PasswordChangedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfullyMessage", resourceCulture);
            }
        }
        
        public static string ResendConfirmationLinkMessage {
            get {
                return ResourceManager.GetString("ResendConfirmationLinkMessage", resourceCulture);
            }
        }
        
        public static string ResetPasswordLinkSentMessage {
            get {
                return ResourceManager.GetString("ResetPasswordLinkSentMessage", resourceCulture);
            }
        }
        
        public static string UserImageCouldNotBeFound {
            get {
                return ResourceManager.GetString("UserImageCouldNotBeFound", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string WaitForResetPasswordEmailResendDelay {
            get {
                return ResourceManager.GetString("WaitForResetPasswordEmailResendDelay", resourceCulture);
            }
        }
        
        public static string TermsAccepted {
            get {
                return ResourceManager.GetString("TermsAccepted", resourceCulture);
            }
        }
        
        public static string YouHaveToAcceptTerms {
            get {
                return ResourceManager.GetString("YouHaveToAcceptTerms", resourceCulture);
            }
        }
        
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        public static string YouNeedToSignIn {
            get {
                return ResourceManager.GetString("YouNeedToSignIn", resourceCulture);
            }
        }
        
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        public static string WaitForConfirmationEmailResendDelay {
            get {
                return ResourceManager.GetString("WaitForConfirmationEmailResendDelay", resourceCulture);
            }
        }
        
        public static string EmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string AreYouSureWannaDelete {
            get {
                return ResourceManager.GetString("AreYouSureWannaDelete", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string UserLockedOut {
            get {
                return ResourceManager.GetString("UserLockedOut", resourceCulture);
            }
        }
        
        public static string UserNameNotFound {
            get {
                return ResourceManager.GetString("UserNameNotFound", resourceCulture);
            }
        }
        
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        public static string AlreadyHaveAccountMessage {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountMessage", resourceCulture);
            }
        }
        
        public static string ConfirmEmailMessage {
            get {
                return ResourceManager.GetString("ConfirmEmailMessage", resourceCulture);
            }
        }
        
        public static string ConfirmEmailTitle {
            get {
                return ResourceManager.GetString("ConfirmEmailTitle", resourceCulture);
            }
        }
        
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        public static string DeleteAccountPrompt {
            get {
                return ResourceManager.GetString("DeleteAccountPrompt", resourceCulture);
            }
        }
        
        public static string DontHaveAccountMessage {
            get {
                return ResourceManager.GetString("DontHaveAccountMessage", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string EmailConfirmationFailedMessage {
            get {
                return ResourceManager.GetString("EmailConfirmationFailedMessage", resourceCulture);
            }
        }
        
        public static string EmailConfirmationTitle {
            get {
                return ResourceManager.GetString("EmailConfirmationTitle", resourceCulture);
            }
        }
        
        public static string EmailConfirmedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("EmailConfirmedSuccessfullyMessage", resourceCulture);
            }
        }
        
        public static string FileUploadFailed {
            get {
                return ResourceManager.GetString("FileUploadFailed", resourceCulture);
            }
        }
        
        public static string ForgetPasswordMessage {
            get {
                return ResourceManager.GetString("ForgetPasswordMessage", resourceCulture);
            }
        }
        
        public static string ForgetPasswordTitle {
            get {
                return ResourceManager.GetString("ForgetPasswordTitle", resourceCulture);
            }
        }
        
        public static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        public static string GenderOther {
            get {
                return ResourceManager.GetString("GenderOther", resourceCulture);
            }
        }
        
        public static string GitHubRepo {
            get {
                return ResourceManager.GetString("GitHubRepo", resourceCulture);
            }
        }
        
        public static string GoToToday {
            get {
                return ResourceManager.GetString("GoToToday", resourceCulture);
            }
        }
        
        public static string HomeMessage {
            get {
                return ResourceManager.GetString("HomeMessage", resourceCulture);
            }
        }
        
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        public static string InvalidConfirmationLinkMessage {
            get {
                return ResourceManager.GetString("InvalidConfirmationLinkMessage", resourceCulture);
            }
        }
        
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string NotReceivedConfirmationEmailMessage {
            get {
                return ResourceManager.GetString("NotReceivedConfirmationEmailMessage", resourceCulture);
            }
        }
        
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        public static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
        
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        public static string ResendEmail {
            get {
                return ResourceManager.GetString("ResendEmail", resourceCulture);
            }
        }
        
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        public static string SignOutPrompt {
            get {
                return ResourceManager.GetString("SignOutPrompt", resourceCulture);
            }
        }
        
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        public static string SingUpTitle {
            get {
                return ResourceManager.GetString("SingUpTitle", resourceCulture);
            }
        }
        
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        public static string TermsMessage {
            get {
                return ResourceManager.GetString("TermsMessage", resourceCulture);
            }
        }
        
        public static string UploadNewProfileImage {
            get {
                return ResourceManager.GetString("UploadNewProfileImage", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string SelectBirthDate {
            get {
                return ResourceManager.GetString("SelectBirthDate", resourceCulture);
            }
        }
        
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string CheckSpamMailMessage {
            get {
                return ResourceManager.GetString("CheckSpamMailMessage", resourceCulture);
            }
        }
        
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        public static string CustomColor {
            get {
                return ResourceManager.GetString("CustomColor", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        public static string SignInAsDifferentUser {
            get {
                return ResourceManager.GetString("SignInAsDifferentUser", resourceCulture);
            }
        }
        
        public static string YouAreSignInAs {
            get {
                return ResourceManager.GetString("YouAreSignInAs", resourceCulture);
            }
        }
        
        public static string ForgotPasswordLink {
            get {
                return ResourceManager.GetString("ForgotPasswordLink", resourceCulture);
            }
        }
        
        public static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
    }
}
